Neos:

  Neos:
    fusion:
      autoInclude:
        'Networkteam.Neos.SelectiveMaintenance': true

    userInterface:
      translation:
        autoInclude:
          'Networkteam.Neos.SelectiveMaintenance':
            - Main
            - 'NodeTypes/*'

