Neos:
  Neos:

    translation:
      autoInclude:
        Networkteam.Neos.SelectiveMaintenance:
          - Main
          - 'NodeTypes/*'

    nodeTypes:
      groups:
        selectiveMaintenance:
          position: end
          label: 'Networkteam.Neos.SelectiveMaintenance:Main:nodeTypes.groups.selectiveMaintenance'
          collapsed: true

